name: Daily Paper Recommendations

on: 
  schedule:
    - cron: '0 6 * * *' # Runs every day at 6 AM UTC, i.e. 8 AM Munich time
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
    daily-paper:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
           python-version: '3.10'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install uv 
            uv venv venv 
            source venv/bin/activate
            uv pip install -r requirements.txt
        - name: Run daily paper script
          env:
            ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
            ZOTERO_LIBRARY_ID: ${{ secrets.ZOTERO_LIBRARY_ID }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
            EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          run: bash run_paper_surf-gh-action.sh
